import { createFileRoute } from "@tanstack/react-router";
import { PageHero } from "@/components/realty/page-hero";
import { CtaBand } from "@/components/realty/cta-band";
import { Reveal } from "@/components/realty/reveal";
import hero from "@/assets/realty-hero.jpg";

export const Route = createFileRoute("/escrow")({ head: () => ({ meta: [
  { title: "Bank-Backed Escrow | Realty Managers" }, { name: "description", content: "Learn how bank-backed escrow arrangements can bring greater structure and visibility to real estate payments." },
  { property: "og:title", content: "Bank-Backed Escrow | Realty Managers" }, { property: "og:description", content: "Explore structured payment safeguards and bank-backed escrow guidance for property transactions." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: EscrowPage });
function EscrowPage() { return <main><PageHero eyebrow="03 / TRANSACTION CONFIDENCE" title="A stronger foundation for every transaction." description="A thoughtful approach to payment safeguards, guided by transparency and structure." image={hero} imageAlt="Residential tower overlooking a coastal city" /><section className="detail-intro"><div className="content-width detail-intro-grid"><Reveal><h2>Confidence is built into the process.</h2></Reveal><Reveal><p>Escrow can help keep funds within a defined framework, with releases governed by agreed conditions and the participating bank’s terms. It is an important conversation to have before a property transaction moves ahead.</p><p>Arrangements depend on the project, bank, applicable regulations, and signed agreements. We can help you understand what questions to ask; we do not hold customer funds.</p></Reveal></div></section><section className="detail-list"><div className="content-width"><Reveal className="section-heading"><div><span className="eyebrow"><span className="eyebrow-line" />THE RIGHT QUESTIONS</span><h2>Structure matters.</h2></div></Reveal>{[["01","Account framework","Understand who operates the escrow account and which bank provides it."],["02","Release conditions","Review the documented milestones and terms that govern how funds are released."],["03","Clear documentation","Keep the bank agreement and transaction records at the center of your decision."]].map(([n,t,d]) => <Reveal key={n}><div className="detail-row"><strong>{n}</strong><h3>{t}</h3><p>{d}</p></div></Reveal>)}</div></section><CtaBand title="Ask before you commit." description="Discuss your transaction and the safeguards you want to understand." /></main>; }
