import { createFileRoute } from "@tanstack/react-router";
import { PageHero } from "@/components/realty/page-hero";
import { CtaBand } from "@/components/realty/cta-band";
import { Reveal } from "@/components/realty/reveal";
import city from "@/assets/realty-city.jpg";

export const Route = createFileRoute("/franchises")({ head: () => ({ meta: [
  { title: "District Franchises | Realty Managers" }, { name: "description", content: "Explore district-level franchise opportunities within the Realty Managers real estate ecosystem." },
  { property: "og:title", content: "District Franchises | Realty Managers" }, { property: "og:description", content: "Grow a locally rooted real estate business within a connected, trust-led network." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: FranchisePage });
function FranchisePage() { return <main><PageHero eyebrow="02 / LOCAL OPPORTUNITY" title="Local knowledge. Wider possibility." description="A district-level franchise approach that values relationships on the ground and the ambition to grow." image={city} imageAlt="Modern residential district at blue hour" /><section className="detail-intro"><div className="content-width detail-intro-grid"><Reveal><h2>Be where opportunity happens.</h2></Reveal><Reveal><p>Every district has its own rhythm, relationships, and real estate potential. Our franchise vision brings local insight into a connected ecosystem designed around credibility and thoughtful growth.</p><p>Interested in representing Realty Managers in your district? Start the conversation and we’ll discuss fit, availability, and the next steps.</p></Reveal></div></section><section className="detail-list"><div className="content-width"><Reveal className="section-heading"><div><span className="eyebrow"><span className="eyebrow-line" />A CONNECTED APPROACH</span><h2>Built to grow together.</h2></div></Reveal>{[["01","District focus","Bring a deep understanding of your local market and the people who shape it."],["02","Shared standards","Operate with an emphasis on transparency, consistency, and responsible guidance."],["03","Mutual opportunity","Explore a partnership model aligned with long-term, sustainable growth."]].map(([n,t,d]) => <Reveal key={n}><div className="detail-row"><strong>{n}</strong><h3>{t}</h3><p>{d}</p></div></Reveal>)}</div></section><CtaBand title="Let’s talk about your district." description="Tell us where you work and what you’re looking to build." /></main>; }
