import { createFileRoute } from "@tanstack/react-router";
import { PageHero } from "@/components/realty/page-hero";
import { CtaBand } from "@/components/realty/cta-band";
import { Reveal } from "@/components/realty/reveal";
import building from "@/assets/realty-building.jpg";

export const Route = createFileRoute("/rera-verification")({ head: () => ({ meta: [
  { title: "RERA Verification | Realty Managers" }, { name: "description", content: "Understand RERA registration details and project documentation before making a property decision with Realty Managers." },
  { property: "og:title", content: "RERA Verification | Realty Managers" }, { property: "og:description", content: "Make more informed property decisions with careful RERA registration and project-documentation review." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ReraPage });
function ReraPage() { return <main><PageHero eyebrow="01 / PROJECT CONFIDENCE" title="Clarity begins with verification." description="Understand the facts behind a project before moving forward." image={building} imageAlt="Contemporary residential building exterior" /><section className="detail-intro"><div className="content-width detail-intro-grid"><Reveal><h2>Look beyond the listing.</h2></Reveal><Reveal><p>RERA registration is an important starting point for evaluating a real estate project. We help you focus on the information worth checking, so you can approach your decision with a clearer view.</p><p>Verification is a review of available records, not a guarantee of a project’s outcome. Official regulator records remain the source of truth.</p></Reveal></div></section><section className="detail-list"><div className="content-width"><Reveal className="section-heading"><div><span className="eyebrow"><span className="eyebrow-line" />THE ESSENTIAL CHECKS</span><h2>What to look for.</h2></div></Reveal>{[["01","Registration details","Compare the project’s registration number and promoter details with the relevant state RERA portal."],["02","Project disclosures","Review published timelines, approvals, and documentation where available."],["03","Informed next steps","Use verified information to frame the right questions before committing."]].map(([n,t,d]) => <Reveal key={n}><div className="detail-row"><strong>{n}</strong><h3>{t}</h3><p>{d}</p></div></Reveal>)}</div></section><CtaBand title="See the full picture first." description="Tell us what you’re considering and we’ll help you identify the right next questions." /></main>; }
