/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FranchisesRouteImport } from './routes/franchises'
import { Route as ManagersRouteImport } from './routes/managers'
import { Route as NriRouteImport } from './routes/nri'
import { Route as ReraVerificationRouteImport } from './routes/rera-verification'
import { Route as SearchResultsRouteImport } from './routes/search-results'
import { Route as CountriesCanadaRouteImport } from './routes/countries.canada'
import { Route as CountriesIndiaRouteImport } from './routes/countries.india'
import { Route as CountriesUsaRouteImport } from './routes/countries.usa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchisesRoute = FranchisesRouteImport.update({
  id: '/franchises',
  path: '/franchises',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersRoute = ManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => rootRouteImport,
} as any)
const NriRoute = NriRouteImport.update({
  id: '/nri',
  path: '/nri',
  getParentRoute: () => rootRouteImport,
} as any)
const ReraVerificationRoute = ReraVerificationRouteImport.update({
  id: '/rera-verification',
  path: '/rera-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsRoute = SearchResultsRouteImport.update({
  id: '/search-results',
  path: '/search-results',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCanadaRoute = CountriesCanadaRouteImport.update({
  id: '/countries/canada',
  path: '/countries/canada',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndiaRoute = CountriesIndiaRouteImport.update({
  id: '/countries/india',
  path: '/countries/india',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesUsaRoute = CountriesUsaRouteImport.update({
  id: '/countries/usa',
  path: '/countries/usa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/franchises': typeof FranchisesRoute
  '/managers': typeof ManagersRoute
  '/nri': typeof NriRoute
  '/rera-verification': typeof ReraVerificationRoute
  '/search-results': typeof SearchResultsRoute
  '/countries/canada': typeof CountriesCanadaRoute
  '/countries/india': typeof CountriesIndiaRoute
  '/countries/usa': typeof CountriesUsaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/franchises': typeof FranchisesRoute
  '/managers': typeof ManagersRoute
  '/nri': typeof NriRoute
  '/rera-verification': typeof ReraVerificationRoute
  '/search-results': typeof SearchResultsRoute
  '/countries/canada': typeof CountriesCanadaRoute
  '/countries/india': typeof CountriesIndiaRoute
  '/countries/usa': typeof CountriesUsaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/franchises': typeof FranchisesRoute
  '/managers': typeof ManagersRoute
  '/nri': typeof NriRoute
  '/rera-verification': typeof ReraVerificationRoute
  '/search-results': typeof SearchResultsRoute
  '/countries/canada': typeof CountriesCanadaRoute
  '/countries/india': typeof CountriesIndiaRoute
  '/countries/usa': typeof CountriesUsaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/franchises'
    | '/managers'
    | '/nri'
    | '/rera-verification'
    | '/search-results'
    | '/countries/canada'
    | '/countries/india'
    | '/countries/usa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact'
    | '/franchises'
    | '/managers'
    | '/nri'
    | '/rera-verification'
    | '/search-results'
    | '/countries/canada'
    | '/countries/india'
    | '/countries/usa'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact'
    | '/franchises'
    | '/managers'
    | '/nri'
    | '/rera-verification'
    | '/search-results'
    | '/countries/canada'
    | '/countries/india'
    | '/countries/usa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  FranchisesRoute: typeof FranchisesRoute
  ManagersRoute: typeof ManagersRoute
  NriRoute: typeof NriRoute
  ReraVerificationRoute: typeof ReraVerificationRoute
  SearchResultsRoute: typeof SearchResultsRoute
  CountriesCanadaRoute: typeof CountriesCanadaRoute
  CountriesIndiaRoute: typeof CountriesIndiaRoute
  CountriesUsaRoute: typeof CountriesUsaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchises': {
      id: '/franchises'
      path: '/franchises'
      fullPath: '/franchises'
      preLoaderRoute: typeof FranchisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers': {
      id: '/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof ManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nri': {
      id: '/nri'
      path: '/nri'
      fullPath: '/nri'
      preLoaderRoute: typeof NriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rera-verification': {
      id: '/rera-verification'
      path: '/rera-verification'
      fullPath: '/rera-verification'
      preLoaderRoute: typeof ReraVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-results': {
      id: '/search-results'
      path: '/search-results'
      fullPath: '/search-results'
      preLoaderRoute: typeof SearchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/canada': {
      id: '/countries/canada'
      path: '/countries/canada'
      fullPath: '/countries/canada'
      preLoaderRoute: typeof CountriesCanadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/india': {
      id: '/countries/india'
      path: '/countries/india'
      fullPath: '/countries/india'
      preLoaderRoute: typeof CountriesIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/usa': {
      id: '/countries/usa'
      path: '/countries/usa'
      fullPath: '/countries/usa'
      preLoaderRoute: typeof CountriesUsaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  FranchisesRoute: FranchisesRoute,
  ManagersRoute: ManagersRoute,
  NriRoute: NriRoute,
  ReraVerificationRoute: ReraVerificationRoute,
  SearchResultsRoute: SearchResultsRoute,
  CountriesCanadaRoute: CountriesCanadaRoute,
  CountriesIndiaRoute: CountriesIndiaRoute,
  CountriesUsaRoute: CountriesUsaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
